### ISSUE TITLE
Problem adding images to Swiper Slider

### ISSUE THREAD

**Issue by skarpik** [2sic/app-swiper#3]
Swiper Slider:  01.01.00
DNN version: 09.06.02
2SXC: 11.05.00
Theme: Bootstrap Instant v04.10.00
Browsers: Chrome, Firefox, Edge

Steps to reproduce problem:

1) Added Swiper Slider instance to a new page. Demo slides appear as expected.

2) Clicked on "pencil" to configure the slider (give the slider a name). Demo slides disappear (as expected). Screenshot of webpage after assigning name:

![Swiper Slider 0](https://user-images.githubusercontent.com/3846223/92857245-6744f980-f3c2-11ea-8bb9-7c42a1c3f041.jpg)

3) Clicked on the "+" to add an image. Image upload dialog does not appear. All links (including main nav) do not respond to mouse clicks. The web page is totally unresponsive. Refreshing the page makes links responsive. Screenshot after clicking on "+":

![Swiper Slider 1](https://user-images.githubusercontent.com/3846223/92857926-63fe3d80-f3c3-11ea-867a-0812c6f4070a.jpg)

4) Workaround is to click on the "pencil"

![Swiper Slider 2](https://user-images.githubusercontent.com/3846223/92858012-8c863780-f3c3-11ea-8c41-1f32f951ee57.jpg)

and then click on "select images for slides":

![Swiper Slider 3](https://user-images.githubusercontent.com/3846223/92858091-a45dbb80-f3c3-11ea-9e13-d3bccd95d74f.JPG)

Images can successfully be added to the Swiper Slider through the "pencil" route.

**Comment by iJungleboy** [comment]
Thanks - do you see an js errors or something when the toolbars don't appear?

**Comment by skarpik** [comment]
Here is what shows up in the console:

[2sxc.dnndev.me-1599824484404.log](https://github.com/2sic/app-swiper/files/5208683/2sxc.dnndev.me-1599824484404.log)

Let me know if there is anything else that I can provide to you.

**Comment by iJungleboy** [comment]
This was a bug in 2sxc 11.05 and is fixed in 11.06

**Comment by skarpik** [comment]
Works perfectly now. Thanks.
